refactor: CI/CD 로직 추가
SWM14-Architect/moview-core-service pull request #37
Opened 2023-07-25 05:40 UTC by ssfic3380

- 모든 branch에 대해서 push가 발생 했을 때마다 테스트를 실행하는 로직 추가
- main에 push를 진행할 때 외에도 직접 deploy 워크플로우를 실행할 수 있도록 로직 변경

2023-07-25 07:28 UTC, westreed requested changes
배포 단계의 조건만 수정하면 될 것 같습니다.

2023-07-25 07:28 UTC, westreed commented on .github/workflows/cicd.yml
> +  # main 외의 브랜치에 대한 push가 발생한 경우에는, 테스트만 진행한다.
main으로 merge하는 경우 외에도, 각자 브랜치에서 작업을 하면서 push했을 때도 테스트해주는 건 좋은 것 같습니다.
직접 테스트를 돌려볼 수 있지만 간혹 깜빡하고 테스트도 돌려보지 않은 채로 PR 날리는 걸 방지해줄 수 있을 것 같네요.

2023-07-25 07:28 UTC, westreed commented on .github/workflows/cicd.yml
> +    if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch'
main, push는 올바르게 된 것 같은데, workflow_dispatch일 때도 main 브랜치인지 검증해봐야 하지 않을까요?
직접 run할 때도 어느 브랜치에서 실행할지 결정할 수 있거든요.

if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'

2023-07-27 06:10 UTC, ssfic3380 commented on .github/workflows/cicd.yml
> +    if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch'
아 다른 브랜치가 배포 될수도 있네요 수정하겠습니다.

2023-07-27 06:18 UTC, westreed approved these changes
테스트 코드가 적절한 타이밍에 작동되도록 잘 작성된 것 같고,
배포 조건 또한 push 뿐만 아니라 workflow에서 run 했을 때도 되도록 잘 바뀐 것 같습니다.

2023-07-27 06:18 UTC, westreed commented on .github/workflows/cicd.yml
> +    if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main'
배포 조건 명시가 잘 된 것 같습니다.

2023-07-27 06:19 UTC, merged