Refactor answer
SWM14-Architect/moview-core-service pull request #79
Opened 2023-09-04 04:53 UTC by dasd412

[한 일]
  <로직>
      1. 데이터 구조 설계한 것 토대로 파이썬 프로젝트 리팩토링 (엔티티)
      2. 데이터 구조 설계한 것 토대로 파이썬 프로젝트 리팩토링 (질문, 답변 리포지토리) + 테스트
      3. 채점 및 평가 프롬프트는 answer 서비스에서 스켈레톤 코드로 만듬.
      4. 서비스, 모듈 전부 싱글톤으로 변경. 그리고 생성자는 DI 방식으로 변경함. 그랬더니 무한로딩 안 남.
      5. 데이터 구조 설계한 것 토대로 파이썬 프로젝트 리팩토링 (답변 서비스) + 테스트
  
  <프롬프트>
      1. 꼬리질문 출제 프롬프트 바꿈.
      2. 대분류 프롬프트 바꿈.
      3. answer에 대분류, 중분류 따로 분리했으므로 중분류  모듈 프롬프트 고침.
      4. Answer 서비스 after 버전 전체 파이프라인 call 성능 측정

2023-09-04 07:57 UTC, westreed requested changes
전체적으로 드리고 싶은 말씀은 string 으로 저장된 objectId를 다루실 때, str(ObjectId(오브젝트ID string)) 으로 감싸서 사용하셨는데 이럴 필요는 없을 것 같습니다!

2023-09-04 07:57 UTC, westreed commented on moview/service/answer_service.py
> +                                     question_id={"question_id": str(ObjectId(question_id))})
여기서 id를 저장할 땐 아래와 같이 하시면 될 것 같습니다.

```python
followup_question = Question(content=followup_question_content, feedback_score=0,
interview_id={
    "#ref": self.interview_repository.collection.name,
    "#id": interview_id, # 이미 스트링으로 넘겨받았으니까 str(ObjectId())를 할 필요는 없을 것 같습니다!
    "#db": self.interview_repository.db.name
},
question_id={
    "#ref": self.question_answer_repository.collection.name,
    "#id": question_id,
    "#db": self.question_answer_repository.db.name
}

2023-09-04 07:57 UTC, westreed commented on moview/service/answer_service.py
> +        return self.filter.exclude_invalid_answer(question=question_content, answer=answer_content)
return 타입이 빠졌습니다!

2023-09-04 07:57 UTC, westreed commented on moview/service/answer_service.py
> +                                                           question_id=question_id, question_content=question_content)
return 타입이 없습니다!

Optional[Tuple[str, str]] 로 표현하면 될 것 같습니다.

2023-09-04 07:57 UTC, westreed commented on tests/repository/test_question_answer_repository.py
> +        question_id = None
여기도 {"#ref" : "collection name", "#id" : "objectID", "#db":"database name"} 형태로 id를 지정해주시면 될 것 같습니다.

2023-09-04 07:57 UTC, westreed commented on tests/repository/test_question_answer_repository.py
> +            ObjectId(initial_question.inserted_id))}, feedback_score=0))
question_id={"#ref" : self.repository.collection.name, "#id" : str(initial_question.inserted_id), "#db":self.repository.db.name}

2023-09-04 07:57 UTC, westreed commented on tests/repository/test_question_answer_repository.py
> +                         {"question_id": str(ObjectId(initial_question.inserted_id))})  # 꼬리 질문은 이전 질문을 가리키고 있어야 한다.
여기도 양식에 맞춰서 다시 쓰시면 될 것 같습니다.

2023-09-04 08:02 UTC, ssfic3380 approved these changes
answer_service가 보기 좋아지고 싱글톤으로 바뀌어서 좋습니다.
이후에 flask를 멀티쓰레드로 작동시켰을 때에도 잘 작동하는지 확인해야 할 것 같습니다.

2023-09-05 01:16 UTC, dasd412 commented on moview/service/answer_service.py
> +                                     question_id={"question_id": str(ObjectId(question_id))})
네 그렇게 바꾸도록 하겠습니다~

2023-09-05 02:04 UTC, dasd412 commented on moview/repository/question_answer/question_answer_repository.py
> +                                         question_id=question_id, created_at=current_time)
이 부분은 결론부터 말하면 보류입니다. ㅠㅠ

이유는 다음과 같습니다.
1. 데이터 구조를 다시 아예 바꿔야 해서 전체 레이어도 그에 맞게 다 바꿔야 합니다.
2. 초기 질문 <- 꼬리질문이여도 순서대로 조회할 수 있습니다.

비교해보면 다음과 같습니다.
[초기 질문 -> 꼬리질문]
1. question_id =None인 것들을 찾는다. (전체 순회이므로 O(n)) 초기질문은 a라 하자.
2. 각 a들에 대해서 fk를 통해 꼬리질문을 이어갑니다. (각 a의 꼬리질문 개수가 평균 m이라 하면 O(m))
3. 따라서 시간 복잡도는 O(mn) ==> O(n^2)

[초기 질문 <- 꼬리 질문]
1. 유니온 파인드 알고리즘을 활용하여 꼬리질문들이 어느 초기 질문에 속하는 지 확인한다. (O(n)에 가까움)
2. interview 엔티티에 순서대로 질문이 저장되므로 해당 부분을 쭉 순회하며 유니온 파인드 자료구조를 참고한다. 그리고 그 순서대로 나열한다. (O(n))
3.  따라서 시간 복잡도는 O(n^2)

2023-09-05 02:04 UTC, dasd412 commented on moview/repository/question_answer/question_answer_repository.py
> +                        question_id=question_id, created_at=current_time)
네 반영할게요!

2023-09-05 02:10 UTC, closed without merging